### ISSUE TITLE
Error in figures task

### ISSUE THREAD

**Issue by haluk** [erbon7/lemon-tree#11]
I followed the tutorial with example data set. It worked until figure task. I'm receiving this error in figure task.

```
LemonTree - Version 3.1.1
-------------------------

Parameters
----------
task:                  figures
data_file:             LemonTree_Tutorial/data/all.txt
reg_file:              LemonTree_Tutorial/data/reg_list.txt
cluster_file:          tight_clusters.txt
tree_file:             results/reg_tf.xml.gz
top_regulators:        results/reg_tf.topreg.txt
use_regulator_mean:    false
use_global_mean:       false
map_file:              null
cut_level:             0
draw_experiment_names: true
draw_experiment_color: null
Reading expression data... [ok]
Number of genes in the data matrix: 600
Number of conditions in the data matrix: 49
Number of missing values in the data matrix: 0
Total number of expression values: 29400
Reading cluster file tight_clusters.txt
 [ok]
Assigned genes: 438
Not assigned genes: 0
Number of clusters: 16
Reading candidate regulators... [ok]
Found 85 regulators belonging to the geneset.
0 of them are discrete
0 regulators do not belong to the gene set
dataMean: -5.700613983491392E-18
dataSigma: 0.9897433186107871
dataMin: -4.22602229528751
dataMax: 4.88876908658967
Reading XML file results/reg_tf.xml.gz [ok]
Reading top regulators classes... results/reg_tf.topreg.txt
GNA11	0	 73.731754
java.io.FileNotFoundException: GNA11	0	 73.731754 (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at lemontree.modulenetwork.ModuleNetwork.setTopRegulatorClasses(ModuleNetwork.java:3286)
	at lemontree.modulenetwork.RunCli.main(RunCli.java:595)

```

**Comment by erbon7** [comment]
Dear Haluk,

I've just tried the figures task from the tutorial on my computer and it works perfectly well. Could you please check all the parameters of your command line and try again ?

**Comment by erbon7** [comment]
closing the issue.
