### ISSUE TITLE
runtime error with version 3.1.0 jar

### ISSUE THREAD

**Issue by erbon7** [erbon7/lemon-tree#8]
Run time error while running version 3.1.0 on tutorial dataset with command:

```
java -jar lemontree.jar \
-task regulators \
-data_file data/expr_matrix.txt \
-reg_file data/reg_list.txt \
-cluster_file tight_clusters.txt \
-output_file reg_tf
```

Error message:

```
LemonTree - Version 3.1.0
-------------------------

Parameters
----------
task:               regulators
data_file:          data/expr_matrix.txt
reg_file:           data/reg_list.txt
cluster_file:       tight_clusters.txt
output_file:        reg_tf
lambda:             0.1
mu:                 0.0
alpha:              0.1
beta:               0.1
num_runs:           1
num_steps:          1100
burn_in:            100
sample_steps:       100
score_gain:         0.0
num_reg:            10
Reading expression data... [ok]
Number of genes in the data matrix: 500
Number of conditions in the data matrix: 49
Number of missing values in the data matrix: 0
Total number of expression values: 24500
Reading cluster file tight_clusters.txt
 [ok]
Assigned genes: 449
Not assigned genes: 0
Number of clusters: 17
Reading candidate regulators... [ok]
Found 85 regulators belonging to the geneset.
0 of them are discrete
0 regulators do not belong to the gene set
Exception in thread "main" java.lang.NullPointerException
	at lemontree.modulenetwork.TreeNode.statistics(TreeNode.java:1271)
	at lemontree.modulenetwork.ModuleNetwork.initStatisticsAndScore(ModuleNetwork.java:3622)
	at lemontree.modulenetwork.RunCli.main(RunCli.java:399)
```

**Comment by erbon7** [comment]
NB : same code and dataset runs fine with version 3.0.5 jar

**Comment by pauerola** [comment]
Added a patch to my branch https://github.com/pauerola/lemon-tree

**Comment by erbon7** [comment]
Ok, problem fixed. 

Thanks a lot Pau for your fast response !
